-- 02_schema_setup.sql
-- Setup schema-level objects: Schemas, Tables, Views, Stages
-- Expected context: Role = Project Role, Database = Project Database

-- 1. Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW COMMENT = 'Landing zone for raw data';
CREATE SCHEMA IF NOT EXISTS ATOMIC COMMENT = 'Normalized and clean data';
CREATE SCHEMA IF NOT EXISTS MMM COMMENT = 'Analytics Mart for Modeling and App';

-- 2. Create Stages
USE SCHEMA ATOMIC;
CREATE STAGE IF NOT EXISTS DATA_STAGE 
    DIRECTORY = (ENABLE = TRUE) 
    COMMENT = 'Stage for raw data files';

CREATE STAGE IF NOT EXISTS MODELS_STAGE 
    DIRECTORY = (ENABLE = TRUE) 
    COMMENT = 'Stage for ML models and notebooks';

-- 3. Create File Formats
CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '');

-- 4. Create Tables in RAW Schema
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS SPRINKLR_DAILY (
    DATE DATE,
    CAMPAIGN_ID VARCHAR(50),
    CHANNEL VARCHAR(50),
    SPEND_AMT FLOAT,
    IMPRESSIONS NUMBER,
    CLICKS NUMBER,
    VIDEO_VIEWS_50 NUMBER
);

CREATE TABLE IF NOT EXISTS SFDC_OPPORTUNITIES (
    OPPORTUNITY_ID VARCHAR(50),
    ACCOUNT_NAME VARCHAR(255),
    LEAD_SOURCE_CAMPAIGN VARCHAR(50),
    STAGE VARCHAR(50),
    AMOUNT_USD FLOAT,
    CREATED_DATE DATE,
    CLOSE_DATE DATE,
    BUSINESS_GROUP VARCHAR(50),
    REGION VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS SAP_ACTUALS (
    INVOICE_ID VARCHAR(50),
    BOOKED_REVENUE FLOAT,
    PROFIT_CENTER VARCHAR(50),
    POSTING_DATE DATE,
    OPPORTUNITY_ID VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS MACRO_INDICATORS (
    DATE DATE,
    PMI_INDEX FLOAT,
    COMPETITOR_SOV FLOAT,
    REGION VARCHAR(50)
);

-- 5. Create Tables in ATOMIC Schema
-- Following ATOMIC conventions: SCD2 versioning + audit columns
USE SCHEMA ATOMIC;

-- ============================================================================
-- DIMENSION TABLES (Reference Data)
-- ============================================================================

-- Geography Hierarchy (Self-referential: Super-Region -> Region -> Country)
CREATE TABLE IF NOT EXISTS GEOGRAPHY (
    GEOGRAPHY_ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    GEOGRAPHY_CODE VARCHAR(50) NOT NULL,
    GEOGRAPHY_NAME VARCHAR(200),
    GEOGRAPHY_TYPE VARCHAR(50) COMMENT 'SUPER_REGION, REGION, COUNTRY',
    PARENT_GEOGRAPHY_ID NUMBER(38,0),
    ISO_COUNTRY_CODE VARCHAR(3),
    ISO_COUNTRY_CODE_2 VARCHAR(2),
    ISO_REGION_CODE VARCHAR(10),
    -- SCD2 Columns
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ DEFAULT '9999-12-31 23:59:59'::TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN DEFAULT TRUE,
    -- Audit Columns
    CREATED_BY_USER VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ,
    PRIMARY KEY (GEOGRAPHY_ID),
    UNIQUE (GEOGRAPHY_CODE, VALID_FROM_TIMESTAMP),
    FOREIGN KEY (PARENT_GEOGRAPHY_ID) REFERENCES GEOGRAPHY(GEOGRAPHY_ID)
);

-- Product Category Hierarchy (Self-referential: Segment -> Division -> Category)
CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORY (
    PRODUCT_CATEGORY_ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    PRODUCT_CATEGORY_CODE VARCHAR(50) NOT NULL,
    CATEGORY_NAME VARCHAR(200),
    CATEGORY_DESCRIPTION VARCHAR(500),
    PARENT_CATEGORY_ID NUMBER(38,0),
    CATEGORY_LEVEL NUMBER(38,0) COMMENT '1=Segment, 2=Division, 3=Category',
    -- SCD2 Columns
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ DEFAULT '9999-12-31 23:59:59'::TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN DEFAULT TRUE,
    -- Audit Columns
    CREATED_BY_USER VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ,
    PRIMARY KEY (PRODUCT_CATEGORY_ID),
    UNIQUE (PRODUCT_CATEGORY_CODE, VALID_FROM_TIMESTAMP),
    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID)
);

-- Organization Hierarchy (Self-referential: Corporate -> Business Group -> Regional BU)
CREATE TABLE IF NOT EXISTS ORGANIZATION (
    ORGANIZATION_ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    ORGANIZATION_CODE VARCHAR(50) NOT NULL,
    ORGANIZATION_NAME VARCHAR(200),
    ORGANIZATION_TYPE VARCHAR(50) COMMENT 'CORPORATE, BUSINESS_GROUP, REGIONAL_BU',
    PARENT_ORGANIZATION_ID NUMBER(38,0),
    ORGANIZATION_LEVEL NUMBER(38,0),
    LEGAL_ENTITY_FLAG BOOLEAN DEFAULT FALSE,
    TAX_ID VARCHAR(50),
    DUNS_NUMBER VARCHAR(13),
    -- SCD2 Columns
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ DEFAULT '9999-12-31 23:59:59'::TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN DEFAULT TRUE,
    -- Audit Columns
    CREATED_BY_USER VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ,
    PRIMARY KEY (ORGANIZATION_ID),
    UNIQUE (ORGANIZATION_CODE, VALID_FROM_TIMESTAMP),
    FOREIGN KEY (PARENT_ORGANIZATION_ID) REFERENCES ORGANIZATION(ORGANIZATION_ID)
);

-- Currency Reference
CREATE TABLE IF NOT EXISTS CURRENCY (
    CURRENCY_ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    CURRENCY_CODE VARCHAR(3) NOT NULL,
    CURRENCY_NAME VARCHAR(100),
    CURRENCY_SYMBOL VARCHAR(5),
    IS_ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (CURRENCY_ID),
    UNIQUE (CURRENCY_CODE)
);

-- ============================================================================
-- MARKETING DIMENSION TABLES (New for MMM)
-- ============================================================================

-- Marketing Channel Dimension
CREATE TABLE IF NOT EXISTS MARKETING_CHANNEL (
    MARKETING_CHANNEL_ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    CHANNEL_CODE VARCHAR(50) NOT NULL COMMENT 'LINKEDIN, GOOGLE_SEARCH, DISPLAY, FACEBOOK',
    CHANNEL_NAME VARCHAR(200),
    CHANNEL_TYPE VARCHAR(50) COMMENT 'SOCIAL, SEARCH, PROGRAMMATIC, EMAIL',
    PLATFORM_CPM NUMBER(18,4) COMMENT 'Benchmark CPM for channel',
    PLATFORM_CTR NUMBER(8,4) COMMENT 'Benchmark CTR for channel',
    -- SCD2 Columns
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ DEFAULT '9999-12-31 23:59:59'::TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN DEFAULT TRUE,
    -- Audit Columns
    CREATED_BY_USER VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ,
    PRIMARY KEY (MARKETING_CHANNEL_ID),
    UNIQUE (CHANNEL_CODE, VALID_FROM_TIMESTAMP)
);

-- Marketing Campaign Dimension (Enhanced with hierarchy FKs)
CREATE TABLE IF NOT EXISTS MARKETING_CAMPAIGN (
    MARKETING_CAMPAIGN_ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    CAMPAIGN_CODE VARCHAR(100) NOT NULL COMMENT 'Taxonomy: SI_EMEA_DE_ABR_LeadGen_CMP-001',
    CAMPAIGN_NAME VARCHAR(200),
    CAMPAIGN_OBJECTIVE VARCHAR(50) COMMENT 'BRAND, LEADGEN, NURTURE',
    -- Foreign Keys to Dimensions
    ORGANIZATION_ID NUMBER(38,0) COMMENT 'FK to ORGANIZATION (Business Unit)',
    PRODUCT_CATEGORY_ID NUMBER(38,0) COMMENT 'FK to PRODUCT_CATEGORY',
    GEOGRAPHY_ID NUMBER(38,0) COMMENT 'FK to GEOGRAPHY',
    MARKETING_CHANNEL_ID NUMBER(38,0) COMMENT 'FK to MARKETING_CHANNEL',
    -- Campaign Details
    START_DATE DATE,
    END_DATE DATE,
    BUDGET_AMOUNT NUMBER(18,2),
    CURRENCY_ID NUMBER(38,0) COMMENT 'FK to CURRENCY',
    -- SCD2 Columns
    VALID_FROM_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VALID_TO_TIMESTAMP TIMESTAMP_NTZ DEFAULT '9999-12-31 23:59:59'::TIMESTAMP_NTZ,
    IS_CURRENT_FLAG BOOLEAN DEFAULT TRUE,
    -- Audit Columns
    CREATED_BY_USER VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY_USER VARCHAR(100),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ,
    PRIMARY KEY (MARKETING_CAMPAIGN_ID),
    UNIQUE (CAMPAIGN_CODE, VALID_FROM_TIMESTAMP),
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ORGANIZATION_ID),
    FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID),
    FOREIGN KEY (GEOGRAPHY_ID) REFERENCES GEOGRAPHY(GEOGRAPHY_ID),
    FOREIGN KEY (MARKETING_CHANNEL_ID) REFERENCES MARKETING_CHANNEL(MARKETING_CHANNEL_ID),
    FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY(CURRENCY_ID)
);

-- ============================================================================
-- MARKETING FACT TABLES (New for MMM)
-- ============================================================================

-- Marketing Media Spend (Daily Grain - Sprinklr Source)
CREATE TABLE IF NOT EXISTS MARKETING_MEDIA_SPEND (
    MARKETING_MEDIA_SPEND_ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    AD_DATE DATE NOT NULL COMMENT 'Daily grain',
    MARKETING_CAMPAIGN_ID NUMBER(38,0) NOT NULL,
    ASSET_TYPE VARCHAR(50) COMMENT 'VIDEO, STATIC, CAROUSEL, WHITEPAPER',
    -- Spend Metrics
    SPEND_USD NUMBER(18,2),
    IMPRESSIONS NUMBER(38,0),
    CLICKS NUMBER(38,0),
    VIDEO_VIEWS_50 NUMBER(38,0),
    ENGAGEMENTS NUMBER(38,0),
    -- Audit Columns
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MARKETING_MEDIA_SPEND_ID),
    FOREIGN KEY (MARKETING_CAMPAIGN_ID) REFERENCES MARKETING_CAMPAIGN(MARKETING_CAMPAIGN_ID)
);

-- Market Indicator (Weekly Grain - External Macro Data)
CREATE TABLE IF NOT EXISTS MARKET_INDICATOR (
    MARKET_INDICATOR_ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    INDICATOR_DATE DATE NOT NULL COMMENT 'Weekly grain',
    GEOGRAPHY_ID NUMBER(38,0) COMMENT 'FK to GEOGRAPHY',
    -- Macro Indicators
    PMI_INDEX NUMBER(5,2) COMMENT 'Purchasing Managers Index',
    COMPETITOR_SHARE_OF_VOICE NUMBER(5,4),
    INDUSTRY_GROWTH_RATE NUMBER(5,4),
    -- Audit Columns
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MARKET_INDICATOR_ID),
    FOREIGN KEY (GEOGRAPHY_ID) REFERENCES GEOGRAPHY(GEOGRAPHY_ID)
);

-- MMM Model Result (ML Output)
CREATE TABLE IF NOT EXISTS MMM_MODEL_RESULT (
    MMM_MODEL_RESULT_ID NUMBER(38,0) NOT NULL AUTOINCREMENT,
    MODEL_RUN_DATE DATE NOT NULL,
    MODEL_VERSION VARCHAR(50),
    -- Dimension FKs (results can be at different granularities)
    MARKETING_CHANNEL_ID NUMBER(38,0),
    ORGANIZATION_ID NUMBER(38,0),
    GEOGRAPHY_ID NUMBER(38,0),
    PRODUCT_CATEGORY_ID NUMBER(38,0),
    -- Model Coefficients and Metrics
    COEFFICIENT_WEIGHT NUMBER(18,6),
    ROI NUMBER(18,4),
    MARGINAL_ROI NUMBER(18,4),
    OPTIMAL_SPEND_SUGGESTION NUMBER(18,2),
    ADSTOCK_DECAY_RATE NUMBER(8,4),
    SATURATION_POINT NUMBER(18,2),
    -- Audit Columns
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MMM_MODEL_RESULT_ID),
    FOREIGN KEY (MARKETING_CHANNEL_ID) REFERENCES MARKETING_CHANNEL(MARKETING_CHANNEL_ID),
    FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION(ORGANIZATION_ID),
    FOREIGN KEY (GEOGRAPHY_ID) REFERENCES GEOGRAPHY(GEOGRAPHY_ID),
    FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(PRODUCT_CATEGORY_ID)
);

-- ============================================================================
-- FLAT STAGING TABLES (For direct data load from source files)
-- These simplified tables support the 03_load_data.sql script
-- ============================================================================

-- Marketing Campaign (Flat - matches campaign_metadata.csv)
CREATE TABLE IF NOT EXISTS MARKETING_CAMPAIGN_FLAT (
    CAMPAIGN_ID VARCHAR(50) NOT NULL,
    CAMPAIGN_NAME VARCHAR(255),
    BUSINESS_GROUP VARCHAR(50),
    REGION VARCHAR(50),
    DIVISION VARCHAR(50),
    CAMPAIGN_TYPE VARCHAR(50),
    CHANNEL VARCHAR(50),
    START_DATE DATE,
    PRIMARY KEY (CAMPAIGN_ID)
);

-- Media Spend Daily (Flat - matches sprinklr_spend.csv)
CREATE TABLE IF NOT EXISTS MEDIA_SPEND_DAILY (
    SPEND_DATE DATE,
    CAMPAIGN_ID VARCHAR(50),
    CHANNEL VARCHAR(50),
    SPEND_AMOUNT FLOAT,
    IMPRESSIONS NUMBER,
    CLICKS NUMBER,
    VIDEO_VIEWS NUMBER
);

-- Opportunity (Flat - matches salesforce_opps.csv)
CREATE TABLE IF NOT EXISTS OPPORTUNITY (
    OPPORTUNITY_ID VARCHAR(50) NOT NULL,
    OPPORTUNITY_NAME VARCHAR(255),
    CAMPAIGN_ID VARCHAR(50),
    STAGE_NAME VARCHAR(50),
    AMOUNT FLOAT,
    CREATED_DATE DATE,
    CLOSE_DATE DATE,
    BUSINESS_UNIT VARCHAR(50),
    PRIMARY KEY (OPPORTUNITY_ID)
);

-- Financial Result (Flat - matches sap_revenue.csv)
CREATE TABLE IF NOT EXISTS ACTUAL_FINANCIAL_RESULT (
    INVOICE_ID VARCHAR(50) NOT NULL,
    OPPORTUNITY_ID VARCHAR(50),
    REVENUE_AMOUNT FLOAT,
    POSTING_DATE DATE,
    PROFIT_CENTER VARCHAR(50),
    PRIMARY KEY (INVOICE_ID)
);

-- Market Signal (Flat - derived from macro_indicators.csv)
CREATE TABLE IF NOT EXISTS MARKET_SIGNAL (
    SIGNAL_DATE DATE,
    SIGNAL_TYPE VARCHAR(50),
    SIGNAL_VALUE FLOAT,
    REGION VARCHAR(50)
);

-- 6. Create DIMENSIONAL Schema for Flattened Views
-- These views flatten hierarchies for easy consumption in modeling and Streamlit
CREATE SCHEMA IF NOT EXISTS DIMENSIONAL COMMENT = 'Flattened dimensional views for analytics';

USE SCHEMA DIMENSIONAL;

-- ============================================================================
-- FLATTENED HIERARCHY VIEWS
-- ============================================================================

-- DIM_GEOGRAPHY_HIERARCHY: Flattens self-referential geography into columns
CREATE OR REPLACE VIEW DIM_GEOGRAPHY_HIERARCHY AS
SELECT 
    g.GEOGRAPHY_ID,
    g.GEOGRAPHY_CODE AS COUNTRY_CODE,
    g.GEOGRAPHY_NAME AS COUNTRY_NAME,
    g.ISO_COUNTRY_CODE,
    g.ISO_COUNTRY_CODE_2,
    r.GEOGRAPHY_ID AS REGION_ID,
    r.GEOGRAPHY_CODE AS REGION_CODE,
    r.GEOGRAPHY_NAME AS REGION_NAME,
    sr.GEOGRAPHY_ID AS SUPER_REGION_ID,
    sr.GEOGRAPHY_CODE AS SUPER_REGION_CODE,
    sr.GEOGRAPHY_NAME AS SUPER_REGION_NAME
FROM ATOMIC.GEOGRAPHY g
LEFT JOIN ATOMIC.GEOGRAPHY r ON g.PARENT_GEOGRAPHY_ID = r.GEOGRAPHY_ID AND r.IS_CURRENT_FLAG = TRUE
LEFT JOIN ATOMIC.GEOGRAPHY sr ON r.PARENT_GEOGRAPHY_ID = sr.GEOGRAPHY_ID AND sr.IS_CURRENT_FLAG = TRUE
WHERE g.IS_CURRENT_FLAG = TRUE 
  AND g.GEOGRAPHY_TYPE = 'COUNTRY';

-- DIM_PRODUCT_HIERARCHY: Flattens product category hierarchy into columns
CREATE OR REPLACE VIEW DIM_PRODUCT_HIERARCHY AS
SELECT
    pc.PRODUCT_CATEGORY_ID,
    pc.PRODUCT_CATEGORY_CODE AS CATEGORY_CODE,
    pc.CATEGORY_NAME,
    div.PRODUCT_CATEGORY_ID AS DIVISION_ID,
    div.PRODUCT_CATEGORY_CODE AS DIVISION_CODE,
    div.CATEGORY_NAME AS DIVISION_NAME,
    seg.PRODUCT_CATEGORY_ID AS SEGMENT_ID,
    seg.PRODUCT_CATEGORY_CODE AS SEGMENT_CODE,
    seg.CATEGORY_NAME AS SEGMENT_NAME
FROM ATOMIC.PRODUCT_CATEGORY pc
LEFT JOIN ATOMIC.PRODUCT_CATEGORY div ON pc.PARENT_CATEGORY_ID = div.PRODUCT_CATEGORY_ID AND div.IS_CURRENT_FLAG = TRUE
LEFT JOIN ATOMIC.PRODUCT_CATEGORY seg ON div.PARENT_CATEGORY_ID = seg.PRODUCT_CATEGORY_ID AND seg.IS_CURRENT_FLAG = TRUE
WHERE pc.IS_CURRENT_FLAG = TRUE 
  AND pc.CATEGORY_LEVEL = 3;

-- DIM_ORGANIZATION_HIERARCHY: Flattens business unit hierarchy
CREATE OR REPLACE VIEW DIM_ORGANIZATION_HIERARCHY AS
SELECT
    o.ORGANIZATION_ID,
    o.ORGANIZATION_CODE AS BU_CODE,
    o.ORGANIZATION_NAME AS BU_NAME,
    bg.ORGANIZATION_ID AS BUSINESS_GROUP_ID,
    bg.ORGANIZATION_CODE AS BUSINESS_GROUP_CODE,
    bg.ORGANIZATION_NAME AS BUSINESS_GROUP_NAME,
    corp.ORGANIZATION_ID AS CORPORATE_ID,
    corp.ORGANIZATION_CODE AS CORPORATE_CODE,
    corp.ORGANIZATION_NAME AS CORPORATE_NAME
FROM ATOMIC.ORGANIZATION o
LEFT JOIN ATOMIC.ORGANIZATION bg ON o.PARENT_ORGANIZATION_ID = bg.ORGANIZATION_ID AND bg.IS_CURRENT_FLAG = TRUE
LEFT JOIN ATOMIC.ORGANIZATION corp ON bg.PARENT_ORGANIZATION_ID = corp.ORGANIZATION_ID AND corp.IS_CURRENT_FLAG = TRUE
WHERE o.IS_CURRENT_FLAG = TRUE;

-- ============================================================================
-- DENORMALIZED DIMENSION VIEWS
-- ============================================================================

-- DIM_CAMPAIGN: Fully denormalized campaign with all dimensional attributes
CREATE OR REPLACE VIEW DIM_CAMPAIGN AS
SELECT
    c.MARKETING_CAMPAIGN_ID,
    c.CAMPAIGN_CODE,
    c.CAMPAIGN_NAME,
    c.CAMPAIGN_OBJECTIVE,
    c.START_DATE,
    c.END_DATE,
    c.BUDGET_AMOUNT,
    -- Channel Attributes
    ch.MARKETING_CHANNEL_ID,
    ch.CHANNEL_CODE,
    ch.CHANNEL_NAME,
    ch.CHANNEL_TYPE,
    -- Geography Attributes (Flattened)
    g.GEOGRAPHY_ID,
    g.COUNTRY_CODE,
    g.COUNTRY_NAME,
    g.REGION_CODE,
    g.REGION_NAME,
    g.SUPER_REGION_CODE,
    g.SUPER_REGION_NAME,
    -- Product Attributes (Flattened)
    p.PRODUCT_CATEGORY_ID,
    p.CATEGORY_CODE,
    p.CATEGORY_NAME,
    p.DIVISION_CODE,
    p.DIVISION_NAME,
    p.SEGMENT_CODE,
    p.SEGMENT_NAME,
    -- Organization Attributes (Flattened)
    o.ORGANIZATION_ID,
    o.BU_CODE,
    o.BU_NAME,
    o.BUSINESS_GROUP_CODE,
    o.BUSINESS_GROUP_NAME
FROM ATOMIC.MARKETING_CAMPAIGN c
LEFT JOIN ATOMIC.MARKETING_CHANNEL ch ON c.MARKETING_CHANNEL_ID = ch.MARKETING_CHANNEL_ID AND ch.IS_CURRENT_FLAG = TRUE
LEFT JOIN DIM_GEOGRAPHY_HIERARCHY g ON c.GEOGRAPHY_ID = g.GEOGRAPHY_ID
LEFT JOIN DIM_PRODUCT_HIERARCHY p ON c.PRODUCT_CATEGORY_ID = p.PRODUCT_CATEGORY_ID
LEFT JOIN DIM_ORGANIZATION_HIERARCHY o ON c.ORGANIZATION_ID = o.ORGANIZATION_ID
WHERE c.IS_CURRENT_FLAG = TRUE;

-- ============================================================================
-- FACT VIEWS FOR STREAMLIT DASHBOARDS (Using Flat Staging Tables)
-- ============================================================================

-- FACT_MEDIA_SPEND_DAILY: Daily spend with campaign attributes (flat version)
CREATE OR REPLACE VIEW FACT_MEDIA_SPEND_DAILY AS
SELECT
    ROW_NUMBER() OVER (ORDER BY s.SPEND_DATE, s.CAMPAIGN_ID) AS SPEND_ID,
    s.SPEND_DATE AS AD_DATE,
    s.SPEND_AMOUNT AS SPEND_USD,
    s.IMPRESSIONS,
    s.CLICKS,
    s.VIDEO_VIEWS,
    0 AS ENGAGEMENTS,
    -- Campaign attributes
    c.CAMPAIGN_ID,
    c.CAMPAIGN_NAME,
    c.CAMPAIGN_TYPE AS CAMPAIGN_OBJECTIVE,
    s.CHANNEL AS CHANNEL_CODE,
    s.CHANNEL AS CHANNEL_NAME,
    CASE 
        WHEN s.CHANNEL IN ('LINKEDIN', 'FACEBOOK') THEN 'SOCIAL'
        WHEN s.CHANNEL IN ('GOOGLE_SEARCH') THEN 'SEARCH'
        WHEN s.CHANNEL IN ('DISPLAY', 'PROGRAMMATIC') THEN 'PROGRAMMATIC'
        ELSE 'OTHER'
    END AS CHANNEL_TYPE,
    c.REGION AS REGION_NAME,
    c.REGION AS SUPER_REGION_NAME,
    NULL AS COUNTRY_CODE,
    NULL AS COUNTRY_NAME,
    NULL AS REGION_CODE,
    NULL AS SUPER_REGION_CODE,
    c.DIVISION AS DIVISION_NAME,
    c.DIVISION AS SEGMENT_NAME,
    NULL AS CATEGORY_CODE,
    NULL AS CATEGORY_NAME,
    NULL AS DIVISION_CODE,
    NULL AS SEGMENT_CODE,
    c.BUSINESS_GROUP AS BU_CODE,
    c.BUSINESS_GROUP AS BU_NAME,
    c.BUSINESS_GROUP AS BUSINESS_GROUP_CODE,
    c.BUSINESS_GROUP AS BUSINESS_GROUP_NAME
FROM ATOMIC.MEDIA_SPEND_DAILY s
LEFT JOIN ATOMIC.MARKETING_CAMPAIGN_FLAT c ON s.CAMPAIGN_ID = c.CAMPAIGN_ID;

-- ============================================================================
-- MMM MODEL INPUT/OUTPUT VIEWS (Using Flat Staging Tables)
-- Revenue is attributed to channels via: Revenue → Opportunity → Campaign → Channel
-- ============================================================================

-- V_MMM_INPUT_WEEKLY: Aggregated weekly grain for MMM Modeling
CREATE OR REPLACE VIEW V_MMM_INPUT_WEEKLY AS
WITH WEEKLY_SPEND AS (
    -- Aggregate spend by week and channel
    SELECT 
        DATE_TRUNC('WEEK', s.SPEND_DATE) AS WEEK_START,
        c.REGION AS REGION_NAME,
        c.CHANNEL AS CHANNEL_CODE,
        CASE 
            WHEN c.CHANNEL = 'LinkedIn' THEN 'SOCIAL'
            WHEN c.CHANNEL = 'Facebook' THEN 'SOCIAL'
            WHEN c.CHANNEL = 'Google Ads' THEN 'SEARCH'
            WHEN c.CHANNEL = 'Programmatic' THEN 'PROGRAMMATIC'
            ELSE 'OTHER'
        END AS CHANNEL_TYPE,
        c.CAMPAIGN_TYPE AS CAMPAIGN_OBJECTIVE,
        SUM(s.SPEND_AMOUNT) AS TOTAL_SPEND,
        SUM(s.IMPRESSIONS) AS TOTAL_IMPRESSIONS,
        SUM(s.CLICKS) AS TOTAL_CLICKS,
        SUM(s.VIDEO_VIEWS) AS TOTAL_VIDEO_VIEWS
    FROM ATOMIC.MEDIA_SPEND_DAILY s
    LEFT JOIN ATOMIC.MARKETING_CAMPAIGN_FLAT c ON s.CAMPAIGN_ID = c.CAMPAIGN_ID
    GROUP BY 1, 2, 3, 4, 5
),
WEEKLY_REVENUE_BY_CHANNEL AS (
    -- Attribute revenue to channels through: Revenue → Opportunity → Campaign → Channel
    SELECT
        DATE_TRUNC('WEEK', r.POSTING_DATE) AS WEEK_START,
        c.REGION AS REGION_NAME,
        c.CHANNEL AS CHANNEL_CODE,
        SUM(r.REVENUE_AMOUNT) AS TOTAL_REVENUE,
        COUNT(DISTINCT r.INVOICE_ID) AS TRANSACTION_COUNT
    FROM ATOMIC.ACTUAL_FINANCIAL_RESULT r
    -- Join to Opportunity to get campaign link
    JOIN ATOMIC.OPPORTUNITY o ON r.OPPORTUNITY_ID = o.OPPORTUNITY_ID
    -- Join to Campaign to get channel
    JOIN ATOMIC.MARKETING_CAMPAIGN_FLAT c ON o.CAMPAIGN_ID = c.CAMPAIGN_ID
    GROUP BY 1, 2, 3
),
WEEKLY_INDICATORS AS (
    SELECT
        DATE_TRUNC('WEEK', ms.SIGNAL_DATE) AS WEEK_START,
        ms.REGION AS REGION_NAME,
        AVG(CASE WHEN ms.SIGNAL_TYPE = 'PMI' THEN ms.SIGNAL_VALUE END) AS AVG_PMI,
        AVG(CASE WHEN ms.SIGNAL_TYPE = 'SOV' THEN ms.SIGNAL_VALUE END) AS AVG_COMPETITOR_SOV
    FROM ATOMIC.MARKET_SIGNAL ms
    GROUP BY 1, 2
)
SELECT
    COALESCE(s.WEEK_START, r.WEEK_START, i.WEEK_START) AS WEEK_START,
    COALESCE(s.REGION_NAME, r.REGION_NAME, i.REGION_NAME) AS SUPER_REGION_NAME,
    COALESCE(s.REGION_NAME, r.REGION_NAME, i.REGION_NAME) AS REGION_NAME,
    NULL AS COUNTRY_NAME,
    NULL AS SEGMENT_NAME,
    NULL AS DIVISION_NAME,
    NULL AS CATEGORY_NAME,
    COALESCE(s.CHANNEL_CODE, r.CHANNEL_CODE) AS CHANNEL_CODE,
    s.CHANNEL_TYPE,
    s.CAMPAIGN_OBJECTIVE,
    -- Spend metrics
    ZEROIFNULL(s.TOTAL_SPEND) AS SPEND,
    ZEROIFNULL(s.TOTAL_IMPRESSIONS) AS IMPRESSIONS,
    ZEROIFNULL(s.TOTAL_CLICKS) AS CLICKS,
    ZEROIFNULL(s.TOTAL_VIDEO_VIEWS) AS VIDEO_VIEWS,
    0 AS ENGAGEMENTS,
    -- Revenue - now properly attributed to channel!
    ZEROIFNULL(r.TOTAL_REVENUE) AS REVENUE,
    -- Control variables
    i.AVG_PMI,
    i.AVG_COMPETITOR_SOV,
    0 AS AVG_INDUSTRY_GROWTH
FROM WEEKLY_SPEND s
FULL OUTER JOIN WEEKLY_REVENUE_BY_CHANNEL r 
    ON s.WEEK_START = r.WEEK_START 
    AND s.REGION_NAME = r.REGION_NAME
    AND s.CHANNEL_CODE = r.CHANNEL_CODE  -- KEY: Join on channel for proper attribution!
LEFT JOIN WEEKLY_INDICATORS i 
    ON COALESCE(s.WEEK_START, r.WEEK_START) = i.WEEK_START 
    AND COALESCE(s.REGION_NAME, r.REGION_NAME) = i.REGION_NAME;

-- ============================================================================
-- 7. Create Views and Tables in MMM Schema
-- ============================================================================
USE SCHEMA MMM;

-- ROI by Channel View (Simple Attribution for Dashboard)
CREATE OR REPLACE VIEW V_ROI_BY_CHANNEL AS
SELECT
    CHANNEL_CODE AS CHANNEL,
    SUM(SPEND) AS TOTAL_SPEND,
    SUM(REVENUE) AS ATTRIBUTED_REVENUE,
    DIV0(SUM(REVENUE), SUM(SPEND)) AS ROAS
FROM DIMENSIONAL.V_MMM_INPUT_WEEKLY
WHERE CHANNEL_CODE IS NOT NULL
GROUP BY 1;

-- ROI by Channel and Region
CREATE OR REPLACE VIEW V_ROI_BY_CHANNEL_REGION AS
SELECT
    CHANNEL_CODE AS CHANNEL,
    SUPER_REGION_NAME,
    REGION_NAME,
    SUM(SPEND) AS TOTAL_SPEND,
    SUM(REVENUE) AS TOTAL_REVENUE,
    DIV0(SUM(REVENUE), SUM(SPEND)) AS ROAS
FROM DIMENSIONAL.V_MMM_INPUT_WEEKLY
WHERE CHANNEL_CODE IS NOT NULL
GROUP BY 1, 2, 3;

-- ROI by Channel and Product Category
CREATE OR REPLACE VIEW V_ROI_BY_CHANNEL_PRODUCT AS
SELECT
    CHANNEL_CODE AS CHANNEL,
    SEGMENT_NAME,
    DIVISION_NAME,
    CATEGORY_NAME,
    SUM(SPEND) AS TOTAL_SPEND,
    SUM(REVENUE) AS TOTAL_REVENUE,
    DIV0(SUM(REVENUE), SUM(SPEND)) AS ROAS
FROM DIMENSIONAL.V_MMM_INPUT_WEEKLY
WHERE CHANNEL_CODE IS NOT NULL
GROUP BY 1, 2, 3, 4;

-- Results tables for Model Output (Enhanced with Uncertainty & Parameters)
CREATE TABLE IF NOT EXISTS MODEL_RESULTS (
    MODEL_VERSION VARCHAR(50),
    CHANNEL VARCHAR(50),
    COEFF_WEIGHT FLOAT,
    ROI FLOAT,
    MARGINAL_ROI FLOAT,
    OPTIMAL_SPEND FLOAT,
    -- Confidence Intervals (90% CI from bootstrap)
    ROI_CI_LOWER FLOAT COMMENT '5th percentile of bootstrap ROI distribution',
    ROI_CI_UPPER FLOAT COMMENT '95th percentile of bootstrap ROI distribution',
    IS_SIGNIFICANT BOOLEAN COMMENT 'TRUE if CI excludes breakeven (1.0)',
    -- Learned Model Parameters
    ADSTOCK_DECAY FLOAT COMMENT 'Geometric decay rate theta (0-1), higher = longer carryover',
    SATURATION_ALPHA FLOAT COMMENT 'Hill function shape parameter, controls curve steepness',
    SATURATION_GAMMA FLOAT COMMENT 'Half-saturation spend level where response = 50% of max',
    -- Model Quality Metrics
    CV_MAPE FLOAT COMMENT 'Cross-validation Mean Absolute Percentage Error',
    R_SQUARED FLOAT COMMENT 'In-sample coefficient of determination',
    N_OBSERVATIONS INT COMMENT 'Number of weekly observations for this channel',
    -- Spend Context
    CURRENT_SPEND FLOAT COMMENT 'Current period total spend for this channel',
    SPEND_SHARE FLOAT COMMENT 'Percentage of total marketing budget'
);

CREATE TABLE IF NOT EXISTS RESPONSE_CURVES (
    MODEL_VERSION VARCHAR(50),
    CHANNEL VARCHAR(50),
    SPEND FLOAT,
    PREDICTED_REVENUE FLOAT,
    -- Confidence bands for response curve
    PREDICTED_REVENUE_CI_LOWER FLOAT COMMENT '5th percentile prediction',
    PREDICTED_REVENUE_CI_UPPER FLOAT COMMENT '95th percentile prediction',
    -- Marginal efficiency at this spend level
    MARGINAL_ROI_AT_SPEND FLOAT COMMENT 'Incremental revenue per incremental dollar at this point',
    -- Zone classification
    EFFICIENCY_ZONE VARCHAR(20) COMMENT 'EFFICIENT, DIMINISHING, or SATURATED'
);

-- View for model results with significance interpretation
CREATE OR REPLACE VIEW V_MODEL_RESULTS_INTERPRETED AS
SELECT
    MODEL_VERSION,
    CHANNEL,
    COEFF_WEIGHT,
    ROI,
    ROI_CI_LOWER,
    ROI_CI_UPPER,
    ROUND(ROI_CI_UPPER - ROI_CI_LOWER, 2) AS CI_WIDTH,
    IS_SIGNIFICANT,
    CASE 
        WHEN IS_SIGNIFICANT AND ROI >= 1.5 THEN 'High Performer'
        WHEN IS_SIGNIFICANT AND ROI >= 1.0 THEN 'Profitable'
        WHEN IS_SIGNIFICANT AND ROI < 1.0 THEN 'Underperforming'
        WHEN NOT IS_SIGNIFICANT THEN 'Uncertain'
        ELSE 'Unknown'
    END AS PERFORMANCE_CATEGORY,
    CASE
        WHEN ROI_CI_UPPER - ROI_CI_LOWER < 0.5 THEN 'High'
        WHEN ROI_CI_UPPER - ROI_CI_LOWER < 1.0 THEN 'Medium'
        ELSE 'Low'
    END AS CONFIDENCE_LEVEL,
    MARGINAL_ROI,
    OPTIMAL_SPEND,
    ADSTOCK_DECAY,
    CASE
        WHEN ADSTOCK_DECAY >= 0.7 THEN 'Long (4+ weeks)'
        WHEN ADSTOCK_DECAY >= 0.4 THEN 'Medium (2-3 weeks)'
        ELSE 'Short (1 week)'
    END AS CARRYOVER_INTERPRETATION,
    SATURATION_ALPHA,
    SATURATION_GAMMA,
    CV_MAPE,
    R_SQUARED,
    N_OBSERVATIONS,
    CURRENT_SPEND,
    SPEND_SHARE
FROM MODEL_RESULTS
WHERE MODEL_VERSION = (SELECT MAX(MODEL_VERSION) FROM MODEL_RESULTS);

-- V_MMM_RESULTS_ANALYSIS: Model results view for DIMENSIONAL schema compatibility
CREATE OR REPLACE VIEW DIMENSIONAL.V_MMM_RESULTS_ANALYSIS AS
SELECT
    ROW_NUMBER() OVER (ORDER BY MODEL_VERSION, CHANNEL) AS MMM_MODEL_RESULT_ID,
    CURRENT_DATE() AS MODEL_RUN_DATE,
    MODEL_VERSION,
    COEFF_WEIGHT AS COEFFICIENT_WEIGHT,
    ROI,
    MARGINAL_ROI,
    OPTIMAL_SPEND AS OPTIMAL_SPEND_SUGGESTION,
    ADSTOCK_DECAY AS ADSTOCK_DECAY_RATE,
    SATURATION_GAMMA AS SATURATION_POINT,
    CHANNEL AS CHANNEL_CODE,
    CHANNEL AS CHANNEL_NAME,
    'MIXED' AS CHANNEL_TYPE,
    NULL AS COUNTRY_CODE,
    NULL AS COUNTRY_NAME,
    NULL AS REGION_CODE,
    NULL AS REGION_NAME,
    NULL AS SUPER_REGION_CODE,
    NULL AS SUPER_REGION_NAME,
    NULL AS CATEGORY_CODE,
    NULL AS CATEGORY_NAME,
    NULL AS DIVISION_CODE,
    NULL AS DIVISION_NAME,
    NULL AS SEGMENT_CODE,
    NULL AS SEGMENT_NAME,
    NULL AS BU_CODE,
    NULL AS BU_NAME,
    NULL AS BUSINESS_GROUP_CODE,
    NULL AS BUSINESS_GROUP_NAME
FROM MMM.MODEL_RESULTS;

-- ============================================================================
-- EVENT TABLE FOR STREAMLIT LOGGING
-- ============================================================================
-- Event tables capture Python logging calls from Streamlit apps
-- View logs via: SELECT * FROM STREAMLIT_DEBUG_EVENTS ORDER BY TIMESTAMP DESC;
CREATE EVENT TABLE IF NOT EXISTS STREAMLIT_DEBUG_EVENTS 
    COMMENT = 'Event table for debugging Streamlit app issues';

SELECT 'Schema setup complete.' as status;

